fetch_key_from_memc is nil out of do block
openresty/lua-ssl-nginx-module pull request #3
Opened 2016-11-09 02:48 UTC by xiewenhui

fetch_key_from_memc is nil out of do block

2016-11-09 07:07 UTC, xiewenhui commented
fix init bug: mv do block to init()

2016-11-09 21:51 UTC, agentzh requested changes

2016-11-09 21:51 UTC, agentzh commented on lualib/ngx/ssl/session/ticket/key_rotation.lua
> +
Extra blank line. We only need a single blank line here.

2016-11-09 21:51 UTC, agentzh commented
Despite the minor coding style thing mentioned above, this looks good to me.

@doujiang24 Will you have a quick look at this?

2016-11-10 03:44 UTC, doujiang24 commented on lualib/ngx/ssl/session/ticket/key_rotation.lua
>  local shdict_name, shm_cache_pos_ttl, shm_cache_neg_ttl, disable_shm_cache
These variables seems no need stay in the top level, maybe we can just move them to `init` function?

2016-11-10 03:44 UTC, doujiang24 commented on lualib/ngx/ssl/session/ticket/key_rotation.lua
>  local shdict_name, shm_cache_pos_ttl, shm_cache_neg_ttl, disable_shm_cache
And we should add `local disable_shm_cache = opts.disable_shm_cache` in `init`.

2016-11-10 04:02 UTC, xiewenhui commented on lualib/ngx/ssl/session/ticket/key_rotation.lua
>  local shdict_name, shm_cache_pos_ttl, shm_cache_neg_ttl, disable_shm_cache
umm，some top level variables can move  to init() func,  @agentzh

2016-11-10 05:41 UTC, xiewenhui commented on lualib/ngx/ssl/session/ticket/key_rotation.lua
>  local shdict_name, shm_cache_pos_ttl, shm_cache_neg_ttl, disable_shm_cache
@agentzh @doujiang24 i made some changes based on your comments.

2016-11-10 09:07 UTC, doujiang24 commented on lualib/ngx/ssl/session/ticket/key_rotation.lua
> +    do
Seems the `do end` is not so necessary here? The local variables can be auto GCed after the function finished.

2016-11-10 09:07 UTC, doujiang24 commented on lualib/ngx/ssl/session/ticket/key_rotation.lua
>      local ctx = {}
Seems the `ctx` in the whole file is useless? remove it also?

2016-11-10 12:41 UTC, xiewenhui commented on lualib/ngx/ssl/session/ticket/key_rotation.lua
>      local ctx = {}
should not,  ctx is used in fetch_key_from_memc func implementation for store memcached obj created

2016-11-10 12:47 UTC, xiewenhui commented on lualib/ngx/ssl/session/ticket/key_rotation.lua
> +    do
actually not so necessary,  but it makes the  initialization more structured and clear.  i prefer to keep 'do ... end' here

2016-11-10 12:55 UTC, xiewenhui commented on lualib/ngx/ssl/session/ticket/key_rotation.lua
>      local ctx = {}
should not, ctx is used in fetch_key_from_memc func implementation for store memcached obj created (for efficiency, reduce temp obj create)

2016-11-10 14:40 UTC, doujiang24 commented on lualib/ngx/ssl/session/ticket/key_rotation.lua
>      local ctx = {}
@xiewenhui Yeah, you are right:) Seems useless only in a few functions like `dlog`, but it seems doesn't matter.

2016-11-10 14:41 UTC, doujiang24 commented on lualib/ngx/ssl/session/ticket/key_rotation.lua
> +    do
Yeah, I'm fine with keep it :)

2016-11-10 18:59 UTC, agentzh commented
Merged. Thanks!

2016-11-10 18:59 UTC, closed without merging